name: Create GitHub Release

on:
  push:
    tags:
    - "*"

jobs:
  release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: "Build Changelog"
      id: github_release
      uses: mikepenz/release-changelog-builder-action@main
      with:
        configuration: ".github/workflows/configuration.json"
        ignorePreReleases: "true"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: ${{ steps.github_release.outputs.changelog }}
        prerelease: ${{ contains(github.ref, '-') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_assets:
    name: Build release assets
    needs: release
    strategy:
      matrix:
        target: ['linux-x64', 'linux-arm64', 'win-x64', 'osx-x64']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: dotnet publish
        run: dotnet publish src/Web/Web.csproj --runtime "${{ matrix.target }}" -c Release --self-contained -o ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            zip -r "hippo-server-${{ matrix.target }}.zip" "${{ matrix.target }}"
          else
            tar czvf "hippo-server-${{ matrix.target }}.tar.gz" "${{ matrix.target }}"
          fi

      - name: Upload binary as GitHub artifact
        if: ${{ matrix.target == 'win-x64' }}
        uses: actions/upload-artifact@v3
        with:
          name: hippo-server
          path: hippo-server-${{ matrix.target }}.zip

      - name: Upload binary as GitHub artifact
        if: ${{ matrix.target != 'win-x64' }}
        uses: actions/upload-artifact@v3
        with:
          name: hippo-server
          path: hippo-server-${{ matrix.target }}.tar.gz

  checksums:
    name: Generate release checksums
    runs-on: ubuntu-latest
    needs: build_assets
    steps:
      - name: download release assets
        uses: actions/download-artifact@v3
        with:
          name: hippo-server

      - name: generate checksums
        run: sha256sum * > checksums.txt

      - uses: actions/upload-artifact@v3
        with:
          name: hippo-server
          path: checksums.txt

  upload_assets:
    name: Upload artifacts to Github release
    runs-on: ubuntu-latest
    needs: checksums
    steps:
      - name: download release assets
        uses: actions/download-artifact@v3
        with:
          name: hippo-server

      - name: Upload Packages to Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*"
